name: 'GCP Cloud Scheduler: Deploy'
description: 'This action helps you in deploying your jobs to GCP Cloud Scheduler.'
inputs:
  jobs_path:
    description: 'Configuration file path of jobs'
    required: true
  group_prefix:
    description: 'Group prefix to use for targeting jobs'
    required: false
    default: ''
  location_id:
    description: 'ID of the location. see: https://cloud.google.com/about/locations/'
    required: true
runs:
  using: 'node12'
  main: 'index.js'